import type { Question } from "@/types/question";

export const questions: Question[] = [
  // ── 深度① あたたかい想起 ─────────────────────────────
  {
    id: "q03",
    title: "初バイトの初日",
    body: "初めてのアルバイト（または初仕事）の初日で、いちばん緊張した瞬間を思い出してみてください。",
    hint: "誰がいたか、何をしたか、どんな気持ちだったか。ひとことでもOKです。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 1,
  },
  {
    id: "q04",
    title: "旅行の失敗談",
    body: "旅行でうまくいかなかった出来事を、ひとつ思い出してみてください。",
    hint: "今思うと笑える話がいちばん素敵です。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 1,
  },
  {
    id: "q05",
    title: "恋のきっかけ",
    body: "誰かを好きになった（または大切な友情が生まれた）「きっかけの瞬間」を思い出してみてください。",
    hint: "恋愛でなくても大丈夫です。友達との出会いでも。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 1,
  },
  {
    id: "q06",
    title: "親の若い頃",
    body: "親が話してくれた「若い頃の話」をひとつ思い出してみてください。",
    hint: "話してもらったことがなくても、想像で書いてみるのもあそびのひとつです。",
    category: "episode",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q07",
    title: "あの頃の遊び",
    body: "子どもの頃、よくやっていた遊びと、一緒にいた人を思い出してみてください。",
    hint: "一人遊びでも、友達との遊びでも。",
    category: "episode",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q08",
    title: "初めての一人暮らし",
    body: "初めて一人暮らしをしたとき、最初に買ったものや最初の夜の記憶を思い出してみてください。",
    hint: "まだ一人暮らしをしたことがなくても、将来の想像で書いてみてください。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 1,
  },
  {
    id: "q10",
    title: "人生の転機",
    body: "人生の道が変わった「あの日」に、何があったか思い出してみてください。",
    hint: "大きな出来事でなくても大丈夫です。小さなきっかけでも。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 1,
  },
  {
    id: "q12",
    title: "タイムカプセル",
    body: "10年前の自分に、タイムカプセルで1つだけ入れるとしたら何ですか？",
    hint: "物でも、言葉でも、写真でも。",
    category: "discover",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q13",
    title: "反対の記憶",
    body: "いつもと違った日を思い出してみてください。何がいつもと違いましたか？",
    hint: "良い日でも、ちょっと変な日でも。",
    category: "discover",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q14",
    title: "名前の由来",
    body: "自分、ペット、または大切な人の名前の由来を思い出してみてください。",
    hint: "由来がわからなくても、「なぜそう呼ばれているか」の想像でOKです。",
    category: "discover",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q16",
    title: "感情の色",
    body: "最近思い出した記憶に、色をつけるとしたら何色ですか？その理由も教えてください。",
    hint: "色の名前が思い浮かばなくても、「夕焼けのような色」でもOKです。",
    category: "discover",
    estimatedMinutes: 1,
    depth: 1,
  },
  {
    id: "q17",
    title: "あの人の口ぐせ",
    body: "思い出す人の決まり文句や、笑い方を思い出してみてください。",
    hint: "誰でもいいです。昔の友達でも、家族でも。",
    category: "discover",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q21",
    title: "音で連想",
    body: "学校のチャイム（または洗濯機の音）を聞いたとき、思い出すことはありますか？",
    hint: "音のイメージが浮かばなくても、連想したことを書いてください。",
    category: "associate",
    senseType: "sound",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q22",
    title: "写真トリガー",
    body: "「古いアルバムの写真」を見たとき、どんな記憶が浮かびますか？",
    hint: "実際の写真がなくても、イメージで自由に書いてください。",
    category: "associate",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q24",
    title: "季節の連想",
    body: "今の季節を思うと、あの頃の何を思い出しますか？",
    hint: "同じ季節の思い出、または今の季節との対比でも。",
    category: "associate",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q25",
    title: "五感ひとつ",
    body: "今日のお題は「匂い」。子どもの頃に好きだった匂いをひとつ思い出してみてください。",
    hint: "食べ物、洗剤、雨の匂い、何でも。",
    category: "sense",
    senseType: "smell",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q26",
    title: "お風呂の記憶",
    body: "お風呂に入ったときの、湯の温度・音・匂い・リラックスした瞬間を思い出してみてください。",
    hint: "ひとつだけでも十分です。",
    category: "sense",
    senseType: "temperature",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q28",
    title: "布の手触り",
    body: "思い出の服、布団、毛布の手触りを思い出してみてください。",
    hint: "言葉で表現するのが難しくても、「ふわふわ」「ざらざら」などでOKです。",
    category: "sense",
    senseType: "touch",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q29",
    title: "夕暮れの色",
    body: "思い出の夕焼けの色と、そのときの気持ちを思い出してみてください。",
    hint: "夕焼けでなくても、空の色の記憶でも。",
    category: "sense",
    senseType: "sight",
    estimatedMinutes: 2,
    depth: 1,
  },
  {
    id: "q30",
    title: "雨の日の感覚",
    body: "雨の日の記憶—傘、靴、窓ガラス、土の匂い…思い出すものを書いてみてください。",
    hint: "雨の日が好きだった・嫌いだった、どちらでも。",
    category: "sense",
    senseType: "smell",
    estimatedMinutes: 2,
    depth: 1,
  },

  // ── 深度② 科学強化（ちょい深度） ───────────────────────
  {
    id: "q01",
    title: "帰り道スケッチ",
    body: "小学校、中学校、高校のいずれかの帰り道で、よく見ていたものを3つ、学校から家に近づく順番で思い出してみてください。",
    hint: "順番が曖昧でも大丈夫。思い出せたものだけ並べてみてください。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 2,
    cognitiveTargets: ["時系列記憶", "空間ナビゲーション"],
  },
  {
    id: "q02",
    title: "教室の座席",
    body: "学生時代、自分の席から見えていたものを3つ思い出し、左から右（または前から後ろ）の順番で書いてみてください。",
    hint: "細かくなくて大丈夫。思い出せたものだけ、並べてみるのがポイントです。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 2,
    cognitiveTargets: ["空間記憶", "視覚的工作記憶"],
  },
  {
    id: "q09",
    title: "文化祭・体育祭",
    body: "文化祭や体育祭の記憶を、朝→昼→終わり頃の順番で3つ思い出してみてください。",
    hint: "参加しなかった年があっても、観客としての記憶でも。順番が入れ替わってもOKです。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 2,
    cognitiveTargets: ["エピソード記憶", "時系列整理"],
  },
  {
    id: "q11",
    title: "共通点さがし",
    body: "「夏」と「初めての仕事」— この2つに共通する思い出を2つ以上見つけてみてください。",
    hint: "無理に見つけなくても大丈夫。浮かんだことをそのまま書いてください。",
    category: "discover",
    estimatedMinutes: 3,
    depth: 2,
    cognitiveTargets: ["認知柔軟性", "抽象化"],
  },
  {
    id: "q15",
    title: "忘れていた宝物",
    body: "最近ふと思い出した「忘れていた記憶」と、それを思い出すきっかけになったものを書いてみてください。",
    hint: "匂い、音、場所…きっかけがわからなくても、記憶だけ書いてOKです。",
    category: "discover",
    estimatedMinutes: 3,
    depth: 2,
    cognitiveTargets: ["想起の連鎖", "多感覚結合"],
  },
  {
    id: "q18",
    title: "地図にピン",
    body: "思い出の場所を2つ思い出し、行った順番（または近い順）で書いてみてください。",
    hint: "正確な住所は不要です。「駅前の公園→コンビニ」のようにざっくりでOKです。",
    category: "discover",
    estimatedMinutes: 3,
    depth: 2,
    cognitiveTargets: ["空間記憶", "順序処理"],
  },
  {
    id: "q19",
    title: "連想リレー",
    body: "「雨」から5つ連想したあと、その中からいちばん古い記憶といちばん最近の記憶をそれぞれ書いてみてください。",
    hint: "つながりがなくてもOK。浮かんだ言葉を並べるだけでも、あなたのあそびです。",
    category: "associate",
    estimatedMinutes: 3,
    depth: 2,
    cognitiveTargets: ["意味記憶ネットワーク", "時間軸の整理"],
  },
  {
    id: "q20",
    title: "匂いで連想",
    body: "「線香の匂い」（または好きな匂い）を思い出したら、その場面の「音」も1つ追加してみてください。",
    hint: "線香でなくても、洗剤・コーヒー・土の匂いなど別の匂いに置き換えてOKです。",
    category: "associate",
    senseType: "smell",
    estimatedMinutes: 3,
    depth: 2,
    cognitiveTargets: ["多感覚結合", "エピソード再構成"],
  },
  {
    id: "q23",
    title: "しりとり記憶",
    body: "最初に思い浮かんだ言葉から、しりとりのように3つ記憶を連想してみてください。",
    hint: "例：「海」→「イルカ」→「カレー」… 正しいしりとりでなくても大丈夫です。",
    category: "associate",
    estimatedMinutes: 3,
    depth: 2,
    cognitiveTargets: ["音韻処理", "連想の切り替え"],
  },
  {
    id: "q27",
    title: "食卓の音",
    body: "家族や大切な人と食べていた頃の「音」と「匂い」を思い出し、それぞれ「食べ物／場所／人」に分類してみてください。",
    hint: "箸の音、テレビの音、料理の匂い… 分類が曖昧でも大丈夫です。",
    category: "sense",
    senseType: "sound",
    estimatedMinutes: 3,
    depth: 2,
    cognitiveTargets: ["カテゴリ化", "多感覚統合"],
  },

  // ── 深度③ 週1の深い宝箱 ───────────────────────────────
  {
    id: "q31",
    title: "二重の思い出",
    body: "子どもの頃の「匂い」を1つ思い出し、その場面の「音」と「場所」も追加してみてください。",
    hint: "3つそろわなくても大丈夫。思い出せたものだけ書いてください。",
    category: "sense",
    senseType: "smell",
    estimatedMinutes: 4,
    depth: 3,
    cognitiveTargets: ["多感覚結合", "エピソード再構成", "二重課題"],
  },
  {
    id: "q32",
    title: "記憶タイムライン",
    body: "子ども・学生・大人の3つの時期から、それぞれ1つずつ記憶を思い出し、古い順に並べてみてください。",
    hint: "時期の区切りが曖昧でもOK。思い出せたものだけ並べてみてください。",
    category: "discover",
    estimatedMinutes: 4,
    depth: 3,
    cognitiveTargets: ["ライフタイム記憶", "時系列処理", "実行機能"],
  },
  {
    id: "q33",
    title: "分類あそび",
    body: "子どもの頃の記憶を5つ思い出し、「食べ物／場所／人／遊び／その他」に分けてみてください。",
    hint: "5つ思い出せなくても、思い出せた分だけ。分類が重なってもOKです。",
    category: "discover",
    estimatedMinutes: 4,
    depth: 3,
    cognitiveTargets: ["カテゴリ流暢性", "意味記憶", "実行機能"],
  },
  {
    id: "q34",
    title: "連想スプリント",
    body: "「夏」を思い浮かべて、関連する言葉や記憶をできるだけ多く書いてみてください（1分ほど）。",
    hint: "数より、思い出す楽しさが大事。止まったら深呼吸して、また書いてみて。",
    category: "associate",
    estimatedMinutes: 3,
    depth: 3,
    cognitiveTargets: ["意味記憶ネットワーク", "処理速度", "持続注意"],
  },
  {
    id: "q35",
    title: "季節スイッチ",
    body: "「夏の記憶」を1つ思い出したら、次に「冬の記憶」に切り替えて1つ思い出してみてください。",
    hint: "季節の切り替えが難しければ、好きな2つのテーマに置き換えてもOKです。",
    category: "associate",
    estimatedMinutes: 4,
    depth: 3,
    cognitiveTargets: ["認知柔軟性", "注意切り替え", "エピソード記憶"],
  },
];

export function getQuestionById(id: string): Question | undefined {
  return questions.find((q) => q.id === id);
}

export function getQuestionsByDepth(depth: 1 | 2 | 3): Question[] {
  return questions.filter((q) => q.depth === depth);
}
