import type { Question } from "@/types/question";

export const questions: Question[] = [
  // ── 深度① 軽い想起 ────────────────────────────────────────
  {
    id: "q03",
    title: "初バイトのドキドキ",
    body: "初めてのアルバイト（または初仕事）の日、胸がドキドキした瞬間を思い出してみてください。",
    hint: "制服、始業前、初めてもらった名札… 細かいことでも。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 1,
    emotionalTone: "surprise",
  },
  {
    id: "q04",
    title: "笑い話になった旅行",
    body: "旅行でうまくいかなかったはずなのに、今でもよく話にする出来事を思い出してみてください。",
    hint: "当時は大変だったことも、一緒に書いてみてください。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 1,
    emotionalTone: "joy",
  },
  {
    id: "q05",
    title: "胸が高鳴った瞬間",
    body: "誰かを好きになった（または大切な友情が生まれた）とき、胸が高鳴った瞬間を思い出してみてください。",
    hint: "恋愛でなくても大丈夫。友達との出会いでも。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 1,
    emotionalTone: "surprise",
  },
  {
    id: "q06",
    title: "親の若い頃",
    body: "親が話してくれた「若い頃の話」で、いちばんおもしろかった話を思い出してみてください。",
    hint: "話してもらったことがなくても、想像で書いてみるのもあそびのひとつです。",
    category: "episode",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "warm",
  },
  {
    id: "q07",
    title: "あの頃の遊び",
    body: "子どもの頃、時間を忘れて夢中になっていた遊びを思い出してみてください。一緒にいた人も書いてみてください。",
    hint: "一人遊びでも、友達との遊びでも。",
    category: "episode",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "joy",
  },
  {
    id: "q08",
    title: "はじめての夜",
    body: "初めて一人暮らしをした（または大きな変化があった）夜、静かで一人だった記憶を思い出してみてください。",
    hint: "まだ経験がなくても、想像で書いてみてください。窓の外、届いたもの、食べたもの…",
    category: "episode",
    estimatedMinutes: 3,
    depth: 1,
    emotionalTone: "melancholy",
  },
  {
    id: "q10",
    title: "人生が動いた日",
    body: "「あ、これで変わるかも」と感じた日を思い出してみてください。何があったか書いてみてください。",
    hint: "大きな出来事でなくても大丈夫。小さなきっかけでも。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 1,
    emotionalTone: "surprise",
  },
  {
    id: "q12",
    title: "タイムカプセル",
    body: "10年前の自分に、タイムカプセルで1つだけ入れるとしたら何ですか？",
    hint: "物でも、言葉でも、写真でも。あの頃の自分に届けたいものを。",
    category: "discover",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "warm",
  },
  {
    id: "q13",
    title: "いつもと違う日",
    body: "いつもと違う、ちょっと不思議な日を思い出してみてください。何がいつもと違いましたか？",
    hint: "良い驚きでも、ちょっと変な日でも。",
    category: "discover",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "surprise",
  },
  {
    id: "q14",
    title: "名前の由来",
    body: "自分、ペット、または大切な人の名前の由来を思い出してみてください。",
    hint: "由来がわからなくても、「なぜそう呼ばれているか」の想像でOKです。",
    category: "discover",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "warm",
  },
  {
    id: "q16",
    title: "思い出の色",
    body: "心に残っている記憶に、色をつけるとしたら何色ですか？その記憶も一緒に書いてみてください。",
    hint: "「夕焼けのような色」など、言葉でうまく表せなくても大丈夫です。",
    category: "discover",
    estimatedMinutes: 1,
    depth: 1,
    emotionalTone: "warm",
  },
  {
    id: "q17",
    title: "あの人の口ぐせ",
    body: "今は会えない、または遠くにいる大切な人の決まり文句や笑い方を思い出してみてください。",
    hint: "会えなくても、思い出すこと自体が、あなたの中で生き続けています。",
    category: "discover",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "melancholy",
  },
  {
    id: "q21",
    title: "あのチャイム",
    body: "学校のチャイム（または放課後のベル）を聞いたとき、どんな気持ちになっていましたか？思い出してみてください。",
    hint: "音が浮かばなくても、帰り道のこと、次の予定… 場面だけでも。",
    category: "associate",
    senseType: "sound",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "nostalgic",
  },
  {
    id: "q22",
    title: "アルバムの1枚",
    body: "古いアルバムの写真で、いちばん好きな1枚（または思い浮かぶ1枚）を思い出してみてください。",
    hint: "実際の写真がなくても、イメージで自由に書いてください。",
    category: "associate",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "nostalgic",
  },
  {
    id: "q24",
    title: "季節の連想",
    body: "今の季節を思うと、あの頃のどんな記憶が浮かびますか？思い出してみてください。",
    hint: "同じ季節の思い出、または今の季節との対比でも。",
    category: "associate",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "nostalgic",
  },
  {
    id: "q25",
    title: "好きだった匂い",
    body: "子どもの頃、好きだった匂いをひとつ思い出してみてください。",
    hint: "食べ物、洗剤、雨のあと… 思い浮かぶものをひとつ。",
    category: "sense",
    senseType: "smell",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "joy",
  },
  {
    id: "q26",
    title: "お風呂の記憶",
    body: "お風呂に入って、湯に浸かっていた瞬間を思い出してみてください。",
    hint: "湯の温度、音、匂い… ひとつだけでも十分です。",
    category: "sense",
    senseType: "temperature",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "warm",
  },
  {
    id: "q28",
    title: "ふわふわの記憶",
    body: "思い出の服、布団、毛布の手触りで、気持ちよかったものを思い出してみてください。",
    hint: "「ふわふわ」「あたたかい」など、感覚の言葉だけでもOKです。",
    category: "sense",
    senseType: "touch",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "warm",
  },
  {
    id: "q29",
    title: "夕暮れの色",
    body: "思い出の夕焼けの色と、そのときの気持ちを思い出してみてください。",
    hint: "夕焼けでなくても、空の色の記憶でも。",
    category: "sense",
    senseType: "sight",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "nostalgic",
  },
  {
    id: "q30",
    title: "雨の日の記憶",
    body: "雨の日に、今も残っている記憶を思い出してみてください。",
    hint: "傘、窓ガラス、土の匂い… 場面や匂いだけでも。",
    category: "sense",
    senseType: "smell",
    estimatedMinutes: 2,
    depth: 1,
    emotionalTone: "melancholy",
  },

  // ── 深度② 科学強化（想起 → 整理の2段階） ─────────────────
  {
    id: "q01",
    title: "帰り道スケッチ",
    body: "小学校、中学校、高校のいずれかの帰り道で、よく見ていたものを3つ、思い出してみてください。それを学校から家に近づく順番で書き出してください。",
    hint: "看板、公園、コンビニ… 景色だけでも十分です。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 2,
    emotionalTone: "nostalgic",
    cognitiveTargets: ["時系列記憶", "空間ナビゲーション"],
  },
  {
    id: "q02",
    title: "教室の座席",
    body: "学生時代、自分の席から見えていたものを3つ、思い出してみてください。それを左から右（または前から後ろ）の順番で書き出してください。",
    hint: "窓の外、黒板、隣の席… 思い浮かぶものを。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 2,
    emotionalTone: "nostalgic",
    cognitiveTargets: ["空間記憶", "視覚的工作記憶"],
  },
  {
    id: "q09",
    title: "文化祭・体育祭",
    body: "文化祭や体育祭で、いちばん印象に残っている記憶を3つ、思い出してみてください。それを朝→昼→終わり頃の順番で書き出してください。",
    hint: "叫んだこと、食べたもの、友達との記憶… 細かいことでも。",
    category: "episode",
    estimatedMinutes: 3,
    depth: 2,
    emotionalTone: "joy",
    cognitiveTargets: ["エピソード記憶", "時系列整理"],
  },
  {
    id: "q11",
    title: "共通点さがし",
    body: "「夏の記憶」と「仕事や学校の記憶」を、それぞれ1つずつ思い出してみてください。書き出したあと、2つに共通するものを見つけてみてください。",
    hint: "まずそれぞれ思い出す、それから共通点を探す。見つからなくても大丈夫です。",
    category: "discover",
    estimatedMinutes: 3,
    depth: 2,
    emotionalTone: "warm",
    cognitiveTargets: ["認知柔軟性", "抽象化"],
  },
  {
    id: "q15",
    title: "忘れていた宝物",
    body: "最近ふと思い出して、「あ、忘れてた！」となった記憶を思い出してみてください。思い出せたら、きっかけになったもの（匂い、音、場所など）を書き足してください。",
    hint: "忘れていた記憶が戻ってくる瞬間は、小さな宝物です。",
    category: "discover",
    estimatedMinutes: 3,
    depth: 2,
    emotionalTone: "joy",
    cognitiveTargets: ["想起の連鎖", "多感覚結合"],
  },
  {
    id: "q18",
    title: "地図にピン",
    body: "「また行きたいな」「ここが好きだった」と思う場所を2つ、思い出してみてください。書き出したあと、行った順番（または近い順）に並べ替えてください。",
    hint: "正確な住所は不要です。「駅前の公園」のようにざっくりでOKです。",
    category: "discover",
    estimatedMinutes: 3,
    depth: 2,
    emotionalTone: "warm",
    cognitiveTargets: ["空間記憶", "順序処理"],
  },
  {
    id: "q19",
    title: "連想リレー",
    body: "「夏」を思い浮かべて、記憶につながる言葉を5つ、自由に書き出してみてください。書き出したあと、いちばん古い記憶といちばん最近の記憶をそれぞれ選んでください。",
    hint: "まず連想する、それから選ぶ。つながりがなくてもOKです。",
    category: "associate",
    estimatedMinutes: 3,
    depth: 2,
    emotionalTone: "nostalgic",
    cognitiveTargets: ["意味記憶ネットワーク", "時間軸の整理"],
  },
  {
    id: "q20",
    title: "匂いで連想",
    body: "子どもの頃、好きだった匂いを思い出し、そのときの場面を書き出してみてください。思い出せたら、その場面の「音」も1つ追加してください。",
    hint: "線香、洗剤、コーヒー、土の匂い… なんでも。",
    category: "associate",
    senseType: "smell",
    estimatedMinutes: 3,
    depth: 2,
    emotionalTone: "warm",
    cognitiveTargets: ["多感覚結合", "エピソード再構成"],
  },
  {
    id: "q23",
    title: "しりとり記憶",
    body: "印象に残っている記憶を3つ、自由に思い出してみてください。書き出したあと、しりとりのように言葉をつなげて並べ替えてみてください。",
    hint: "例：「海」→「イルカ」→「カレー」… 正しいしりとりでなくても大丈夫です。",
    category: "associate",
    estimatedMinutes: 3,
    depth: 2,
    emotionalTone: "joy",
    cognitiveTargets: ["音韻処理", "連想の切り替え"],
  },
  {
    id: "q27",
    title: "食卓の音",
    body: "家族や大切な人と食べていた頃の「音」と「匂い」を思い出してみてください。書き出したあと、それぞれを「食べ物／場所／人」に分類してみてください。",
    hint: "箸の音、笑い声、料理の匂い… ひとつでも。",
    category: "sense",
    senseType: "sound",
    estimatedMinutes: 3,
    depth: 2,
    emotionalTone: "warm",
    cognitiveTargets: ["カテゴリ化", "多感覚統合"],
  },

  // ── 深度③ 週1の深い宝箱 ───────────────────────────────
  {
    id: "q31",
    title: "二重の思い出",
    body: "子どもの頃、好きだった「匂い」を1つ思い出してください。思い出せたら、その場面の「音」と「場所」も書き足してください。",
    hint: "3つそろわなくても大丈夫。浮かんだものだけで。",
    category: "sense",
    senseType: "smell",
    estimatedMinutes: 4,
    depth: 3,
    emotionalTone: "warm",
    cognitiveTargets: ["多感覚結合", "エピソード再構成", "二重課題"],
  },
  {
    id: "q32",
    title: "記憶タイムライン",
    body: "子ども・学生・大人の3つの時期から、それぞれ印象に残っている記憶を1つずつ思い出してください。書き出したあと、古い順に並べ替えてください。",
    hint: "時期の区切りが曖昧でもOK。思い出せたものだけ並べてみてください。",
    category: "discover",
    estimatedMinutes: 4,
    depth: 3,
    emotionalTone: "nostalgic",
    cognitiveTargets: ["ライフタイム記憶", "時系列処理", "実行機能"],
  },
  {
    id: "q33",
    title: "分類あそび",
    body: "子どもの頃の記憶を5つ思い出してください。書き出したあと、「食べ物／場所／人／遊び／その他」に分けてみてください。",
    hint: "5つ思い出せなくても、思い出せた分だけ。分類が重なってもOKです。",
    category: "discover",
    estimatedMinutes: 4,
    depth: 3,
    emotionalTone: "joy",
    cognitiveTargets: ["カテゴリ流暢性", "意味記憶", "実行機能"],
  },
  {
    id: "q34",
    title: "連想スプリント",
    body: "「夏」を思い浮かべて、記憶につながる言葉を、できるだけ多く書き出してみてください（1分ほど）。",
    hint: "止まったら深呼吸して、また書いてみて。数より浮かんだもので。",
    category: "associate",
    estimatedMinutes: 3,
    depth: 3,
    emotionalTone: "joy",
    cognitiveTargets: ["意味記憶ネットワーク", "処理速度", "持続注意"],
  },
  {
    id: "q35",
    title: "季節スイッチ",
    body: "「夏の記憶」を1つ思い出してください。思い出せたら、次に「冬の記憶」に切り替えて1つ思い出してください。",
    hint: "季節の切り替えが難しければ、好きな2つのテーマに置き換えてもOKです。",
    category: "associate",
    estimatedMinutes: 4,
    depth: 3,
    emotionalTone: "warm",
    cognitiveTargets: ["認知柔軟性", "注意切り替え", "エピソード記憶"],
  },
];

export function getQuestionById(id: string): Question | undefined {
  return questions.find((q) => q.id === id);
}

export function getQuestionsByDepth(depth: 1 | 2 | 3): Question[] {
  return questions.filter((q) => q.depth === depth);
}

export function isEdgeTone(tone: Question["emotionalTone"]): boolean {
  return tone === "surprise" || tone === "melancholy";
}
